# Google Meet MCP Server v3.0 - Local Development (Simplified)
# Ultra-simple Docker Compose for quick local development
version: '3.8'

services:
  google-meet-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: google-meet-mcp-simple
    restart: unless-stopped
    
    # Simple environment configuration
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
    
    # Load credentials from local env file
    env_file:
      - .env.local
    
    # Minimal volume mounts
    volumes:
      - ./src:/app/src:ro  # Hot reload source code
      - ./credentials.json:/app/credentials.json:ro
      - ./token.json:/app/token.json:rw
    
    # Expose health check port
    ports:
      - "9090:9090"
    
    # Interactive development
    stdin_open: true
    tty: true
    
    # Simplified health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/health"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 10s

# No volumes or networks - keep it simple