/**
 * Central export for all TypeScript types
 * Google Meet MCP Server Type Definitions
 */

// Google APIs
export type {
  GoogleOAuth2Client,
  GoogleTokens,
  AuthUrlOptions,
  GoogleCalendarClient,
  GoogleAuthOAuth2Instance,
  GoogleCalendarInstance,
  CalendarListResponse,
  GoogleCalendar,
  EventListParams,
  EventListResponse,
  EventGetParams,
  EventResponse,
  EventInsertParams,
  EventUpdateParams,
  EventDeleteParams,
  GoogleCalendarEvent,
  EventDateTime,
  EventAttendee,
  ConferenceData,
  ConferenceEntryPoint,
  MeetSpace,
  SpaceConfig,
  ModerationRestrictions,
  ArtifactConfig,
  ActiveConference,
  ConferenceRecord,
  Recording,
  DriveDestination,
  Transcript,
  DocsDestination,
  TranscriptEntry,
  Participant,
  AnonymousUser,
  PhoneUser,
  ParticipantSession,
  GoogleApiError,
  NodeError
} from './google-apis.js';

// MCP Server specific types
export type {
  MeetServerConfig,
  AuthConfig,
  MeetConfig,
  LogLevel,
  ListCalendarsInput,
  ListEventsInput,
  GetEventInput,
  CreateEventInput,
  UpdateEventInput,
  DeleteEventInput,
  CreateSpaceInput,
  GetSpaceInput,
  UpdateSpaceInput,
  EndActiveConferenceInput,
  ListConferenceRecordsInput,
  GetConferenceRecordInput,
  ListRecordingsInput,
  GetRecordingInput,
  ListTranscriptsInput,
  GetTranscriptInput,
  ListTranscriptEntriesInput,
  GetParticipantInput,
  ListParticipantsInput,
  GetParticipantSessionInput,
  ListParticipantSessionsInput,
  GuestPermissions,
  CreateMeetingOptions,
  EventUpdateData,
  SpaceUpdateData,
  ProcessedCalendar,
  ProcessedEvent,
  RestClientOptions,
  RestResponse,
  ValidationResult,
  ServerInfo,
  ServerCapabilities,
  McpServerOptions
} from './mcp-server.js';

// Utility types
export type {
  Optional,
  RequiredOnly,
  DeepPartial,
  NonEmptyArray,
  Prettify,
  PromiseResolve,
  PromiseReject,
  AsyncFunction,
  ISODateString,
  TimeZone,
  ValidatedInput,
  HttpMethod,
  HttpStatusCode,
  ErrorWithCode,
  ErrorResponse,
  NodeEnv,
  ProcessEnv,
  JsonPrimitive,
  JsonObject,
  JsonArray,
  JsonValue,
  FilePath,
  FileContent,
  FileReadOptions,
  FileWriteOptions,
  EventId,
  CalendarId,
  SpaceName,
  ConferenceRecordName,
  RecordingName,
  TranscriptName,
  ParticipantName,
  ArrayElement,
  KeysOfType,
  PickByType,
  Handler,
  EventHandler,
  ErrorHandler,
  ToolDefinition,
  ToolResult,
  ToolRequest
} from './utilities.js';

// Testing types
export type {
  MockReadFile,
  MockWriteFile,
  MockFetch,
  MockOAuth2Client,
  MockCalendarClient,
  MockResponse,
  MockError
} from './testing.js';